import express from 'express';
import pool from '../mysql.js';
import axios from 'axios';
import { redis } from '../../index.js';

const router = express.Router();

/**
 * @swagger
 * /generate:
 *   post:
 *     summary: Generate SQL from natural language
 *     description: Sends a natural language query to the AI service, converts it to SQL, executes it, and returns the result.
 *     tags:
 *       - SQL Generator
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - query
 *             properties:
 *               query:
 *                 type: string
 *                 example: Show all customers from NY
 *     responses:
 *       200:
 *         description: SQL and results
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 sql:
 *                   type: string
 *                   example: SELECT * FROM customers WHERE state = 'NY';
 *                 results:
 *                   type: array
 *                   items:
 *                     type: object
 *                   example:
 *                     - id: 1
 *                       name: John Doe
 *                       state: NY
 *                     - id: 2
 *                       name: Jane Smith
 *                       state: NY
 *                 rowCount:
 *                   type: integer
 *                   example: 2
 *       400:
 *         description: Missing query or SQL execution failed
 *       500:
 *         description: Internal server or database error
 *       503:
 *         description: AI service is unavailable
 */

router.post('/', async (req, res) => {
    const { query } = req.body;

    if (!query) {
        return res.status(400).json({ error: 'No query provided' });
    }

    const cacheKey = `query:${query}`;

    try {
        // Check Redis Cache
        const cachedResult = await redis.get(cacheKey);
        if (cachedResult) {
            return res.json({ source: 'cache', ...JSON.parse(cachedResult) });
        }

        // Check AI service health
        const aiServiceUrl = process.env.AI_SERVICE_URL || 'http://localhost:8000';

        try {
            await axios.get(`${aiServiceUrl}/health`, { timeout: 5000 });
        } catch (healthError) {
            return res.status(503).json({
                error: 'AI service unavailable',
                details: `Cannot connect to AI service at ${aiServiceUrl}. Error: ${healthError.message}`
            });
        }

        // Generate SQL using AI
        const aiResponse = await axios.post(
            `${aiServiceUrl}/generate`,
            { query },
            {
                headers: { 'Content-Type': 'application/json' },
                timeout: 1600000
            }
        );

        const sql = aiResponse.data.sql;

        if (!sql) {
            return res.status(500).json({ error: 'No SQL generated by AI service' });
        }

        // Check DB connection
        try {
            await pool.query('SELECT 1');
        } catch (dbTestError) {
            return res.status(500).json({
                error: 'Database connection failed',
                details: dbTestError.message
            });
        }

        // Execute SQL
        try {
            const [results] = await pool.query(sql);
            const finalResult = {
                sql,
                results,
                rowCount: results.length
            };

            // Cache the result in Redis
            await redis.set(cacheKey, JSON.stringify(finalResult), 'EX', 3600); // 1 hour expiry

            return res.json(finalResult);
        } catch (sqlError) {
            return res.status(400).json({
                error: 'SQL execution failed',
                sql: sql,
                details: sqlError.message
            });
        }

    } catch (error) {
        if (error.code === 'ECONNREFUSED') {
            return res.status(503).json({
                error: 'Service unavailable',
                details: `Cannot connect to required service. ${error.message}`
            });
        } else if (error.response) {
            return res.status(error.response.status || 500).json({
                error: 'Service error',
                details: error.response.data
            });
        } else {
            return res.status(500).json({
                error: 'Internal server error',
                details: error.message,
                stack: process.env.NODE_ENV === 'development' ? error.stack : undefined
            });
        }
    }
});

export default router;
